Mv 286 limit displayed video tiles
membraneframework/membrane_videoroom pull request #132
Opened 2023-02-20 12:57 UTC by pkrucz00

2023-02-21 15:01 UTC, kamil-stasiak requested changes

2023-02-23 13:02 UTC, pkrucz00 commented on assets/src/pages/room/components/StreamPlayer/PinnedTilesSection.tsx
> +  const mapMediaTileConfigToElement = (pinnedTile: MediaPlayerTileConfig) => {
Ad. 2a - isn't this important only if the component has it's own independent state? If it's a simple "map" like the example above, I don't think the placement of the component makes any difference.

2023-03-03 15:05 UTC, bblaszkow06 commented
Converted to draft as it is blocked by MV-288

2023-06-16 14:47 UTC, bblaszkow06 commented
Closed in favour of #182

2023-06-16 14:47 UTC, closed without merging