Add missing dependencies to readme
membraneframework/membrane_videoroom pull request #147
Opened 2023-03-02 11:43 UTC by ostatni5

2023-03-02 11:45 UTC, kamil-stasiak approved these changes

2023-03-02 12:02 UTC, bblaszkow06 requested changes

2023-03-02 12:02 UTC, bblaszkow06 commented on README.md
> +`EXTERNAL_IP` should be set to the local IP address of the computer this is running on. `EXTERNAL_IP` is optional.
Without it you won't be able to connect from outside of `localhost`. I'd rather rephrase this like:
```suggestion
`EXTERNAL_IP` should be set to the local IP address of the computer this is running on.
It is required unless you only connect via `localhost`.
```

2023-03-03 09:58 UTC, bblaszkow06 approved these changes

2023-03-03 11:42 UTC, merged