Turn on/off simulcast in config
membraneframework/membrane_videoroom pull request #34
Opened 2022-07-20 12:26 UTC by Rados13

This PR introduces two changes:

- you can turn on/off simulcast by, changing the config variable,
- to show simulcast it on click `Backspace`

2022-07-21 15:15 UTC, bblaszkow06 commented
* As discussed it would be better to use some other key for showing controls (or a button)
* It seems we might need to work on both versions for some time, so it would be best to have both variants available, e.g. by adding query parameter `?simulcast=true` or using a different URL (`simulcast/room/id`)

2022-08-01 13:33 UTC, mickel8 requested changes

2022-08-01 13:33 UTC, mickel8 commented on assets/src/room.ts
> +    // window.history.replaceState(null, "", window.location.pathname);
Is this needed?

2022-08-01 13:33 UTC, mickel8 commented on assets/src/room_ui.ts
> +simulcastControlsBtn.hidden = true
I think this should be in `setupControls`

2022-08-01 13:33 UTC, mickel8 commented on lib/videoroom/room.ex
> +    simulcast? = Application.fetch_env!(:membrane_videoroom_demo, :simulcast?)
As discussed let's move this on the client side and change query param into checkbox

2022-08-04 15:33 UTC, mickel8 approved these changes

2022-08-04 15:33 UTC, mickel8 commented on lib/videoroom_web/controllers/page_controller.ex
> +    simulcast? = Map.get(params, "simulcast", false) == ""
This should be always present, shouldn't it?

2022-08-04 15:33 UTC, mickel8 commented on assets/src/room_ui.ts
> +const simulcastControlsBtn = simulcastControls.querySelector("button") as HTMLButtonElement;
Could we format `TS` format?

2022-08-04 15:33 UTC, mickel8 commented on assets/src/room_ui.ts
> +    changeVisibilityRemoteSimulcastControls(feed, !showSimulcast);
Why do we negate `showSimulcast`?

2022-08-04 15:33 UTC, mickel8 commented on assets/src/room_ui.ts
> +    setShowSimulcast(state.showSimulcast);
This button should be visible only when simulcast was enabled so we can do
```suggestion
    changeVisibilitySimulcastControlls(!state.showSimulcast)
```    

and delete `setShowSimulcast`

2022-08-04 15:33 UTC, mickel8 commented on assets/src/room_ui.ts
> +  simulcastControls.hidden = true
```suggestion
  simulcastControlsBtnDiv.hidden = true
```
Also, do we have to hide button when we have already hide the whole div?

2022-08-04 15:34 UTC, mickel8 approved these changes

2022-08-10 15:46 UTC, bblaszkow06 requested changes

2022-08-10 15:46 UTC, bblaszkow06 commented on lib/videoroom_web/controllers/room_controller.ex
> +  def index(conn, %{"room_id" => id, "display_name" => _name} = params) do
Warning: unused variable

2022-08-11 09:01 UTC, bblaszkow06 approved these changes

2022-08-16 12:10 UTC, maciejewskakatarzyna requested changes
## 3 bugs below:

### BUG 1
**Description**: 
Mobile: bottom controls are squeezed and simulcast controls cover up the video (screen)

**Steps to reproduce:**
Create a room on mobile with at least one person and simulcast turned on.
Click "Show simulcast controls" button.

**Expected situation:** 
Videoroom controls should be not squeezed (circle) and visible. 
Simulcast controls and video should be visible.

**Environment:** 
iOS: Chrome, Safari (iPhone 12)
Android: Chrome (Samsung A53)

![IMG_3895](https://user-images.githubusercontent.com/52798715/184875986-318b4cd5-b900-4edb-8c6a-903819ddc8c6.PNG)

----------

### BUG 2
**Description**: 
Mobile: simulcast controls for another peer are not visible (screen)

**Steps to reproduce:**
Create a room on mobile with at least two people and simulcast turned on.
Click "Show simulcast controls" button.

**Expected situation:** 
Simulcast controls should be visible for both users.

**Environment:** 
iOS: Chrome, Safari (iPhone 12)
Android: Chrome (Samsung A53)

![IMG_3896](https://user-images.githubusercontent.com/52798715/184876586-6e8334fc-90ca-4b36-80bf-6c7b839f08e7.PNG)

-----------

### BUG 3
**Description**: 
Simulcast controls are visible after joining the room with simulcast checkbox unchecked (video)

**Steps to reproduce:**
Create a room with at least one person and simulcast turned on.
Leave the room.
Uncheck simulcast checkbox.
Join the room.
Click "Show simulcast controls" button.

**Expected situation:** 
Simulcast controls shouldn't be visible after joining the room with simulcast checkbox unchecked.

**Environment:** 
macOS: Chrome, Safari
iOS: Chrome, Safari (iPhone 12)
Android: Chrome (Samsung A53)

https://user-images.githubusercontent.com/52798715/184877372-ef679afc-f176-450c-9985-e04b5d89cef0.mov

2022-08-22 06:52 UTC, maciejewskakatarzyna commented on lib/videoroom_web/templates/room/index.html.heex
> +                    <div name="video-encoding", class="absolute text-green-700/100 text-shadow-lg bg-white top-0 right-0 p-2", style="color: green, font-size: 20px">Encoding: m</div>
FIXED

2022-08-26 12:57 UTC, maciejewskakatarzyna approved these changes

2022-08-29 10:40 UTC, merged