Mv 246 video tile redesign
membraneframework/membrane_videoroom pull request #93
Opened 2023-01-27 10:45 UTC by pkrucz00

In this PR:
  - the video tile is restyled
  - camera icon is deleted and a screen with user's initials is displayed while the camera is off
  - the micOff icon has be refurbrished
  - the name tag has been restyled
  - video content is trimmed when the user has a horizontal video input source but there is padding (background is visible and there is no trimming) if the source is vertical or the user shares the screen

2023-01-30 08:51 UTC, alexmaar approved these changes

2023-01-31 09:45 UTC, kamil-stasiak requested changes

2023-01-31 09:45 UTC, kamil-stasiak commented on assets/src/pages/room/components/StreamPlayer/MediaPlayer.tsx
> +  screenShare,
please rename screenShare to something like"allowFillContent" or "blockFillContetn" to make it more generic

2023-01-31 09:45 UTC, kamil-stasiak commented on assets/src/pages/room/components/StreamPlayer/MediaPlayerPeersSection.tsx
> +            cameraOffImage={showDisabledIcon(video) ? <InitialsImage initials={config.initials} /> : null}
I think we can simplify it. Take a look at: https://github.com/membraneframework/membrane_videoroom/pull/96/files

2023-01-31 10:34 UTC, kamil-stasiak approved these changes

2023-01-31 10:35 UTC, merged